import type { AgentBudget } from './models/AgentBudget.js';
import { PnLTracker } from './PnLTracker.js';
import { DynamicBudgetEngine, type RecalibrationResult } from './DynamicBudgetEngine.js';
/**
 * Detailed insights generated by the FeedbackIntegrationLayer.
 */
export interface FeedbackInsights {
    agentId: string;
    inefficiencies: string[];
    utilizationPatterns: string[];
    performanceSummary: {
        totalRevenue: number;
        totalCosts: number;
        netPnL: number;
        averageRoi: number;
        successRate: number;
    };
}
/**
 * FeedbackIntegrationLayer
 * Bridge between real-world PnL outcomes and the DynamicBudgetEngine.
 * Analyzes historical performance to inform future budget allocations.
 */
export declare class FeedbackIntegrationLayer {
    private pnlTracker;
    private budgetEngine;
    constructor(pnlTracker: PnLTracker, budgetEngine: DynamicBudgetEngine);
    /**
     * Processes PnL results for an agent and triggers a budget recalibration.
     * @param budget The current agent budget record.
     * @returns The recalibration result and generated insights.
     */
    processFeedback(budget: AgentBudget): {
        recalibrationResult: RecalibrationResult;
        insights: FeedbackInsights;
    };
    /**
     * Converts a list of PnL log entries into the structured format expected by the DynamicBudgetEngine.
     */
    private mapLedgerToRecalibrationInput;
    /**
     * Flags inefficiencies and utilization patterns by analyzing the ledger and current budget.
     */
    private analyzePatterns;
}
//# sourceMappingURL=FeedbackIntegrationLayer.d.ts.map